---
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.8
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    - repo: https://github.com/jendrikseipp/vulture
      rev: v2.7
      hooks:
          - id: vulture
            args:
                - main.py
                - --min-confidence
                - "80"
                - --exclude
                - "test_*.py"

    - repo: https://github.com/rhysd/actionlint
      rev: v1.6.26
      hooks:
          - id: actionlint

    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.9.0.6
      hooks:
          - id: shellcheck

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            types_or: [toml]
            args: ["--write"]

    - repo: local
      hooks:
          - id: python-test
            name: "python: tests"
            description: "Run python tests (excluding slow tests)"
            entry: uv run pytest -m "not slow" --tb=short
            language: system
            types: [python]
            pass_filenames: false
            stages: [manual]
